# Generated by Django 5.0.1 on 2025-07-09 19:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название документа"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["txt", "docx", "xlsx"]
                            )
                        ],
                        verbose_name="Файл",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Обработан"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_text", models.TextField(verbose_name="Оригинальный текст")),
                (
                    "sentence_number",
                    models.PositiveIntegerField(verbose_name="Номер предложения"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Не подтвержден"),
                            (1, "Подтвердил переводчик"),
                            (2, "Подтвердил корректор"),
                        ],
                        default=0,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_sentences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Назначено переводчику",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        to="translations.document",
                        verbose_name="Документ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение",
                "verbose_name_plural": "Предложения",
                "ordering": ["document", "sentence_number"],
                "unique_together": {("document", "sentence_number")},
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translated_text",
                    models.TextField(verbose_name="Переведенный текст"),
                ),
                (
                    "translator_notes",
                    models.TextField(blank=True, verbose_name="Заметки переводчика"),
                ),
                (
                    "corrector_notes",
                    models.TextField(blank=True, verbose_name="Заметки корректора"),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, verbose_name="Одобрен корректором"
                    ),
                ),
                (
                    "is_rejected",
                    models.BooleanField(
                        default=False, verbose_name="Отклонен корректором"
                    ),
                ),
                (
                    "translated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата перевода"
                    ),
                ),
                (
                    "corrected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата корректировки"
                    ),
                ),
                (
                    "corrector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corrected_translations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Корректор",
                    ),
                ),
                (
                    "sentence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation",
                        to="translations.sentence",
                        verbose_name="Предложение",
                    ),
                ),
                (
                    "translator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Переводчик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перевод",
                "verbose_name_plural": "Переводы",
                "ordering": ["-translated_at"],
            },
        ),
        migrations.CreateModel(
            name="TranslationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translated_text", models.TextField(verbose_name="Текст перевода")),
                ("action", models.CharField(max_length=50, verbose_name="Действие")),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="translations.translation",
                        verbose_name="Перевод",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "История перевода",
                "verbose_name_plural": "История переводов",
                "ordering": ["-created_at"],
            },
        ),
    ]
