# Generated by Django 5.0.1 on 2025-07-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="translation",
            name="corrector_notes",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="is_rejected",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="translator_notes",
        ),
        migrations.AddField(
            model_name="translation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает проверки"),
                    ("approved", "Утверждено"),
                    ("rejected", "Отклонено"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
