# Generated by Django 5.0.1 on 2025-07-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Администратор"),
                    ("representative", "Представитель республики"),
                    ("translator", "Переводчик"),
                    ("corrector", "Корректор"),
                ],
                default="translator",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
