# Generated by Django 5.0.1 on 2025-07-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0002_remove_translation_corrector_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="title",
        ),
    ]
