# Generated by Django 5.0.1 on 2025-07-17 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0003_remove_document_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="translation",
            name="corrector",
        ),
        migrations.AddField(
            model_name="sentence",
            name="corrector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_corrections",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Назначено корректору",
            ),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Не подтвержден"),
                    (1, "Подтвердил переводчик"),
                    (2, "Подтвердил корректор"),
                    (3, "Отклонено корректором"),
                ],
                default=0,
                verbose_name="Статус",
            ),
        ),
    ]
