# Generated by Django 5.0.1 on 2025-07-30 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0004_remove_translation_corrector_sentence_corrector_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="corrector",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "corrector"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrected_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Корректор",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[("pending", "В обработке"), ("translated", "Переведен"), ("corrected", "Проверен")],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="translator",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "translator"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="translated_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Переводчик",
            ),
        ),
    ]
