# Generated by Django 5.0.1 on 2025-07-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0005_document_corrector_document_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["file"], "verbose_name": "Документ", "verbose_name_plural": "Документы"},
        ),
    ]
