# Generated by Django 5.0.1 on 2025-07-31 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0006_alter_document_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="corrector",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "corrector"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrected_translations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Корректор",
            ),
        ),
    ]
